// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-directions/BloomGarden.tsx": () => import("../components/mockups/brand-directions/BloomGarden.tsx"),
  "./components/mockups/brand-directions/MaisonFleur.tsx": () => import("../components/mockups/brand-directions/MaisonFleur.tsx"),
  "./components/mockups/brand-directions/PetalIvory.tsx": () => import("../components/mockups/brand-directions/PetalIvory.tsx")
};
